GET http://localhost:3000/api/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NjY1ODQ1OCwiZXhwIjoxNjQ2NjYyMDU4fQ.u7AIY6I8hVl4wMkuVpE3PZHuTubcIkxF4YWQX2aZhQ0

###
POST http://localhost:3000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NjY1ODM0OSwiZXhwIjoxNjQ2NjYxOTQ5fQ.nTioZHfx9VTMRgL4OdZJgaezOhLsb2lapjvRmHyEm1A
Content-Type: application/json

{
    "projectName": "okejbror"
}
###

PUT http://localhost:3000/api/project/34
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NjY1ODM0OSwiZXhwIjoxNjQ2NjYxOTQ5fQ.nTioZHfx9VTMRgL4OdZJgaezOhLsb2lapjvRmHyEm1A
Content-Type: application/json

{
    "projectName": "ETETE"
}
###

DELETE http://localhost:3000/api/project/37
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NjY1ODM0OSwiZXhwIjoxNjQ2NjYxOTQ5fQ.nTioZHfx9VTMRgL4OdZJgaezOhLsb2lapjvRmHyEm1A
//Content-Type: application/json

###

POST http://localhost:3000/api/tokens
Content-Type: application/json

{
    "grant_type": "password",
    "username": "tenniswille96@live.se",
    "password": "dinmamma1"
}